/*
 * ThemeResourcesGenerator is a simple Java application that creates appmap.xml from 
 * the appfilter.xml file.
 * This file is not automatically generated by the icon request tool on Polar
 * but is required by LG Home Launcher to apply icons.
 *
 * Created by Francesco Baldan with NetBeans IDE
 */
package com.baldan.francesco;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Scanner;

/**
 * Appmapp Generator
 * @author Francesco Baldan
 */
public class ThemeResourcesGenerator {

    /**
     * @param args the command line arguments
     * @throws java.io.FileNotFoundException
     */
    public static void main(String[] args) throws FileNotFoundException {
        
        // The two strings contain the name of the the file where I took the
        // infos and the name of the generated file
        
        final String APPFILTER = "appfilter.xml";
        final String THEME_RESOURCES = "theme_resources.xml";
        
        // Creation of the two objects needed to read appfilter.xml and
        // to generate theme_resources.xml
        
        File inputFile = new File(APPFILTER);
        Scanner in = new Scanner(inputFile);
        PrintWriter out = new PrintWriter(THEME_RESOURCES);
        
        // Creating the theme_resources.xml file
        while (in.hasNextLine()) {
            String line = in.nextLine();
            out.println(line
                    .replace("resources", "Theme version=\"1\"")  // Replace all "resources" word with "Theme version="1""
                    .replace("item", "AppIcon")  // Replace all "item" word with "AppIcon"
                    .replace("component", "name")  // Replace all "component" word with "name"
                    .replace("ComponentInfo{", "")  //Remove a part of the string that is not needed
                    .replace("}", "")  //Remove a part of the string that is not needed
                    .replace("drawable", "image")  // Replace all "drawable" word with "image"
                    .replace("/resources", "/Theme")  // Replace all "/resources" word with "/Theme"
                    .replace("<iconback img1=\"iconback\" />", "<Label value=\"Polar\" />")  // Replace an unusued string with a needed string
                    .replace("<iconmask img1=\"iconmask\" />", "<Wallpaper image=\"polar_wallpaper\" />")  // Replace an unusued string with a needed string
                    .replace("<iconupon img1=\"iconupon\" />", "<LockScreenWallpaper image=\"polar_wallpaper\" />")  // Replace an unusued string with a needed string
                    .replace("<scale factor=\"1.0\" />", "<ThemePreview image=\"polar_preview\" />\n    <ThemePreviewWork image=\"polar_preview\" />\n    <ThemePreviewMenu image=\"polar_preview\" />\n    <DockMenuAppIcon selector=\"half_green\" />\n\n    <!-- This is how to format this xml to get your icons to work with LG Home -->"));  // Replace an unusued string with some needed strings
        }
        
        // Close the opened objects
        in.close();
        out.close(); 
    }
}
